### ISSUE TITLE
Problem with Navigation Example 

### ISSUE THREAD

**Issue by lacie-life** [NVIDIA-Omniverse/IsaacSim-ros_workspaces#5]
Hello, I met a problem when running the navigation script with the example in [7.2.8. ROS2 Navigation](https://docs.omniverse.nvidia.com/isaacsim/latest/ros2_tutorials/tutorial_ros2_navigation.html)

I install ROS 2-Humble following [the ROS 2 install and configuration with Isaac Sim](https://docs.omniverse.nvidia.com/isaacsim/latest/installation/install_ros.html)

Here is my environment information for re-produce error

OS: Ubuntu 22.04
ROS2 Distributor: Humble
WorkSpace Location: [IsaacSim-ros_workspaces](https://github.com/NVIDIA-Omniverse/IsaacSim-ros_workspaces)
Isaac Sim: 2023.1.1

Command:

```
ros2 launch carter_navigation carter_navigation.launch.py
```

Output:

```
[INFO] [launch]: All log files can be found below /home/lacie/.ros/log/2024-03-22-17-49-28-505698-lacie-life-3837280
[INFO] [launch]: Default logging verbosity is set to INFO
[ERROR] [launch]: Caught exception in launch (see debug for traceback): "package 'pointcloud_to_laserscan' not found, searching: ['/home/lacie/workspaces/IsaacSim-ros_workspaces/humble_ws/install/isaac_tutorials', '/home/lacie/workspaces/IsaacSim-ros_workspaces/humble_ws/install/isaac_ros_navigation_goal', '/home/lacie/workspaces/IsaacSim-ros_workspaces/humble_ws/install/isaac_ros2_messages', '/home/lacie/workspaces/IsaacSim-ros_workspaces/humble_ws/install/custom_message', '/home/lacie/workspaces/IsaacSim-ros_workspaces/humble_ws/install/carter_navigation', '/opt/ros/humble']"
[INFO] [rviz2-1]: process started with pid [3837291]
[INFO] [component_container_isolated-2]: process started with pid [3837293]
[component_container_isolated-2] [INFO] [1711097369.165438867] [nav2_container]: Load Library: /opt/ros/humble/lib/libmap_server_core.so
[component_container_isolated-2] [INFO] [1711097369.172568963] [nav2_container]: Found class: rclcpp_components::NodeFactoryTemplate<nav2_map_server::CostmapFilterInfoServer>
[component_container_isolated-2] [INFO] [1711097369.172595697] [nav2_container]: Found class: rclcpp_components::NodeFactoryTemplate<nav2_map_server::MapSaver>
[component_container_isolated-2] [INFO] [1711097369.172597776] [nav2_container]: Found class: rclcpp_components::NodeFactoryTemplate<nav2_map_server::MapServer>
[component_container_isolated-2] [INFO] [1711097369.172599592] [nav2_container]: Instantiate class: rclcpp_components::NodeFactoryTemplate<nav2_map_server::MapServer>
[component_container_isolated-2] [INFO] [1711097369.175122496] [map_server]: 
[component_container_isolated-2] 	map_server lifecycle node launched. 
[component_container_isolated-2] 	Waiting on external lifecycle transitions to activate
[component_container_isolated-2] 	See https://design.ros2.org/articles/node_lifecycle.html for more information.
[component_container_isolated-2] [INFO] [1711097369.175141716] [map_server]: Creating
[INFO] [rviz2-1]: sending signal 'SIGINT' to process[rviz2-1]
[INFO] [component_container_isolated-2]: sending signal 'SIGINT' to process[component_container_isolated-2]
[component_container_isolated-2] [INFO] [1711097369.178046962] [rclcpp]: signal_handler(signum=2)
[component_container_isolated-2] [INFO] [1711097369.178079718] [map_server]: Running Nav2 LifecycleNode rcl preshutdown (map_server)
[component_container_isolated-2] [INFO] [1711097369.178098841] [map_server]: Destroying bond (map_server) to lifecycle manager.
[ERROR] [rviz2-1]: process has died [pid 3837291, exit code -2, cmd '/opt/ros/humble/lib/rviz2/rviz2 -d /home/lacie/workspaces/IsaacSim-ros_workspaces/humble_ws/install/carter_navigation/share/carter_navigation/rviz2/carter_navigation.rviz --ros-args'].
[ERROR] [launch]: Caught exception in launch (see debug for traceback): Cannot shutdown a ROS adapter that is not running
[ERROR] [launch]: Caught exception in launch (see debug for traceback): cannot use Destroyable because destruction was requested
[WARNING] [launch_ros.actions.load_composable_nodes]: Abandoning wait for the '/nav2_container/_container/load_node' service response, due to shutdown.
Future exception was never retrieved
future: <Future finished exception=InvalidHandle('cannot use Destroyable because destruction was requested')>
Traceback (most recent call last):
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/ros/humble/lib/python3.10/site-packages/launch_ros/actions/load_composable_nodes.py", line 197, in _load_in_sequence
    self._load_node(next_load_node_request, context)
  File "/opt/ros/humble/lib/python3.10/site-packages/launch_ros/actions/load_composable_nodes.py", line 119, in _load_node
    while not self.__rclpy_load_node_client.wait_for_service(timeout_sec=1.0):
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/client.py", line 180, in wait_for_service
    return self.service_is_ready()
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/client.py", line 159, in service_is_ready
    with self.handle:
rclpy._rclpy_pybind11.InvalidHandle: cannot use Destroyable because destruction was requested
[ERROR] [component_container_isolated-2]: process[component_container_isolated-2] failed to terminate '5' seconds after receiving 'SIGINT', escalating to 'SIGTERM'
[INFO] [component_container_isolated-2]: sending signal 'SIGTERM' to process[component_container_isolated-2]
[component_container_isolated-2] [INFO] [1711097374.181358543] [rclcpp]: signal_handler(signum=15)
[ERROR] [component_container_isolated-2]: process[component_container_isolated-2] failed to terminate '10.0' seconds after receiving 'SIGTERM', escalating to 'SIGKILL'
[INFO] [component_container_isolated-2]: sending signal 'SIGKILL' to process[component_container_isolated-2]

```
I also tried it with multi-robot example and met the same error, after checking something, I can run the script when commenting pointcloud_to_laserscan node. I don't know exactly the problem. 

Do you have any suggestions for me? 
Many thanks!

**Comment by ayushgnv** [comment]
It looks like `pointcloud_to_laserscan` package is not installed on your system. Could you try the steps provided [here](https://docs.omniverse.nvidia.com/isaacsim/latest/installation/install_ros.html#setting-up-workspaces) to build the workspace including the rosdep commands which will ensure you have all necessary packages installed on the system?
